PlutusData and lossless Aeson decoding
Plutonomicon/cardano-browser-tx pull request #150
Opened 2022-02-27 10:29 UTC by klntsky

Please check the JS part very carefully.

2022-02-28 11:45 UTC, ngua approved these changes
The JSON manipulation and related stuff looks good. I still think it's a good idea to include the type/kind signatures and explicit imports for consistency with the rest of the codebase

I'm going to approve this anyway so it doesn't get held up though

2022-02-28 12:34 UTC, adamczykm commented on src/QueryM.purs
> +  -- TODO: replace it with the new implementation in `Aeson`.
:+1:

2022-02-28 12:42 UTC, adamczykm requested changes
- We should now use the new machinery to decode all JSONs. Am I right?
- The `parseJsonStringifyNumbers` can now be removed maybe the entire Helpers module if `fromJustEff` can be replaced by an existing function.
- I think we should expand the test suite. Tests from  test/Helpers.purs stress the js algorithm's ability to handle edge cases in string vs number recognition. They can be reused.

2022-03-02 03:50 UTC, ngua commented
@adamczykm We have a separate issue to replace the existing stringified numbers JSON stuff (#151), so we can address that in a separate PR I think

2022-03-02 10:32 UTC, adamczykm commented
What about the tests?

2022-03-03 09:07 UTC, ngua commented
@adamczykm We can just re-use the tests from the `Helpers` module when #151 gets done. I don't think we should block this PR on doing that though

2022-03-03 13:38 UTC, adamczykm approved these changes
Do you intend to use the 'comments PR'

2022-03-04 04:48 UTC, merged